# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76bcf3681def932b55b3f84aea7c35b1aa96be2865cb736db24c23d8dba9ee04d3671397e900fd4b92bc0c9ef345b0e9ad20a800b165ee6fb4747a8c0ea6d821

test:
  secret_key_base: 35655664f39c11faa58d559cfc3d938baf7caabdebcde4e89b30c434f52f2dc6e11c7c72132552c86f9e596dc0802fb7beb8af0fff432757f07e666e9b1c6f34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
